# Generated by Django 3.0.5 on 2020-04-19 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('total_discount', models.IntegerField(default=0)),
                ('delivery_fee', models.IntegerField(default=0)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_detail', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price_per_item', models.IntegerField(default=0)),
                ('sell_count', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
                ('product_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductItem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_item_id',
            field=models.ManyToManyField(related_name='OrderItems', through='orders.OrderItems', to='products.ProductItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
